version: '{build}'
branches:
  only:
  - master
clone_depth: 10
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
matrix:
  fast_finish: true
environment:
  PYTHON: "C:\\Python34-x64"
  PYTHON_VERSION: "3.4.3"
  PYTHON_ARCH: "64"

  BIN_INSTALL_DIR: C:\Install\bin
  LIB_INSTALL_DIR: C:\Install\lib
  INCLUDE_INSTALL_DIR: C:\Install\include

  matrix:
    - GENERATOR: "Visual Studio 13"
      ARCH: 32
    - GENERATOR: "Visual Studio 13"
      ARCH: 64
install:
- ps: |
    if (-not (Test-Path "C:\ProgramData\chocolatey\lib\winflexbison3")) {
      & choco install winflexbison3
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    }
build_script:
- ps: |
    mkdir build
    cmake -LAH . -Bbuild -G "Visual Studio 12 2013"
    msbuild /p:Configuration=Release build/mtex2MML.sln
test_script:
- ps: |
    cd build
    ctest -V
