version: '{build}'
branches:
  only:
  - master
clone_depth: 10
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
image:
- Visual Studio 2017
build:
  parallel: true
platform:
- x64
- x86
environment:
  PYTHON: "C:\\Python34-x64"
  PYTHON_VERSION: "3.4.3"
  PYTHON_ARCH: "64"
install:
- ps: |
    if (-not (Test-Path "C:\ProgramData\chocolatey\lib\winflexbison3")) {
      & choco install winflexbison3
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    }
    if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
    $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
build_script:
- cmake -G "%CMAKE_GENERATOR%" -A "%CMAKE_ARCH%" .
- msbuild /p:Configuration=Release mtex2MML.sln
test_script:
- ctest -V .
